CREATE TABLE `evaluations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`pocPosto` varchar(255),
	`pocNome` varchar(255),
	`pocContacto` varchar(255),
	`despacho` text,
	`mandadoDetencao` int DEFAULT 0,
	`mandadoBusca` int DEFAULT 0,
	`quantidadeSuspeitos` varchar(10),
	`modalidadeIsolado` int DEFAULT 0,
	`modalidadeAssociacao` int DEFAULT 0,
	`tipoCriminal` varchar(50),
	`antecedentesContraPessoas` int DEFAULT 0,
	`antecedentesContraPatrimonio` int DEFAULT 0,
	`antecedentesOutros` int DEFAULT 0,
	`antecedentesFSS` varchar(10),
	`posseArma` varchar(50),
	`usoArma` varchar(50),
	`tipologiaApartamento` int DEFAULT 0,
	`tipologiaMoradia` int DEFAULT 0,
	`tipologiaOutro` int DEFAULT 0,
	`contextoIsolado` int DEFAULT 0,
	`contextoBairroSocial` int DEFAULT 0,
	`contextoMeioUrbano` int DEFAULT 0,
	`contextoMeioRural` int DEFAULT 0,
	`segurancaCaes` int DEFAULT 0,
	`segurancaPortaBlindada` int DEFAULT 0,
	`segurancaOutrasMedidas` int DEFAULT 0,
	`avaliador` varchar(255),
	`dataAvaliacao` varchar(20),
	`parecer` text,
	`pontuacao` int NOT NULL DEFAULT 0,
	`neop` varchar(20) NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `evaluations_id` PRIMARY KEY(`id`)
);
