CREATE TABLE `operations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`evaluationId` int NOT NULL,
	`userId` int NOT NULL,
	`refFiledoc` varchar(255),
	`operacaoNumero` varchar(50),
	`preenchimentoSecOp` varchar(50),
	`cmdtOp` varchar(255),
	`dataOp` varchar(20),
	`tipoEmpenho` varchar(50),
	`missao` text,
	`entidadeSolicitadora` varchar(50),
	`local` text,
	`obsReuniao` text,
	`gdhSaidaUI` varchar(50),
	`gdhEntradaUI` varchar(50),
	`cmdtForcaReuniao` varchar(255),
	`indicativoRadioReuniao` varchar(50),
	`efetivTotalReuniao` varchar(50),
	`viaturasCaracterizadasReuniao` int DEFAULT 0,
	`viaturasDescaracterizadasReuniao` int DEFAULT 0,
	`viaturasEspeciaisReuniao` int DEFAULT 0,
	`kmTotaisReuniao` varchar(50),
	`cterOperacao` varchar(255),
	`dterOperacao` varchar(255),
	`pterZaOperacao` varchar(255),
	`gdhInicioOperacao` varchar(50),
	`gdhChegadaUIOperacao` varchar(50),
	`cmdtForcaOperacao` varchar(255),
	`indicativoRadioOperacao` varchar(50),
	`efetivTotalOperacao` varchar(50),
	`viaturasCaracterizadasOperacao` int DEFAULT 0,
	`viaturasDescaracterizadasOperacao` int DEFAULT 0,
	`viaturasEspeciaisOperacao` int DEFAULT 0,
	`kmTotaisOperacao` varchar(50),
	`itpTipo` varchar(50),
	`gdhInicioITP` varchar(50),
	`gdhFimITP` varchar(50),
	`forcaTitularInqueritos` int DEFAULT 0,
	`custosPortagens` text,
	`custosCombustiveis` text,
	`obsVisados` text,
	`municoesArmasAuto762` int DEFAULT 0,
	`municoesArmasAuto9mm` int DEFAULT 0,
	`municoesArmasAuto762mm` int DEFAULT 0,
	`municoesArmasAuto556mm` int DEFAULT 0,
	`municoesArmasAuto556` int DEFAULT 0,
	`municoesCacadeiraBarracha` int DEFAULT 0,
	`municoesCacadeiraChumbo` int DEFAULT 0,
	`municoesCacadeiraBeamBag` int DEFAULT 0,
	`municoesCacadeiraZagalote` int DEFAULT 0,
	`municoesCacadeiraZinco` int DEFAULT 0,
	`municoesRevolverASP` int DEFAULT 0,
	`taserCargaX26` int DEFAULT 0,
	`taserGranadaFlashBang1Estalo` int DEFAULT 0,
	`taserGranadaFlashBang1Estalo2Bang` int DEFAULT 0,
	`taserGranadaFlashBang2Estalos2Bangs` int DEFAULT 0,
	`taserGranadaFlashBangMultiplos` int DEFAULT 0,
	`taserAlgemas` varchar(50),
	`obsConsumos` text,
	`obsSECOp` text,
	`regSECOp` varchar(255),
	`excelSECOp` tinyint DEFAULT 0,
	`apontamentosNotas` text,
	`croquis` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `operations_id` PRIMARY KEY(`id`)
);
