import { pgTable, pgEnum, serial, integer, varchar, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core"

export const roleEnum = pgEnum("role", ["user", "admin"]);

export const evaluations = pgTable("evaluations", {
	  id: serial().primaryKey().notNull(),
	  userId: integer().notNull(),
	  pocPosto: varchar({ length: 255 }),
	  pocNome: varchar({ length: 255 }),
	  pocContacto: varchar({ length: 255 }),
	  despacho: text(),
	  mandadoDetencao: integer().default(0),
	  mandadoBusca: integer().default(0),
	  quantidadeSuspeitos: varchar({ length: 10 }),
	  modalidadeIsolado: integer().default(0),
	  modalidadeAssociacao: integer().default(0),
	  tipoCriminal: varchar({ length: 255 }),
	  antecedentesContraPessoas: integer().default(0),
	  antecedentesContraPatrimonio: integer().default(0),
	  antecedentesOutros: integer().default(0),
	  antecedentesFss: varchar("antecedentesFSS", { length: 10 }),
	  posseArma: varchar({ length: 50 }),
	  usoArma: varchar({ length: 50 }),
	  tipologiaApartamento: integer().default(0),
	  tipologiaMoradia: integer().default(0),
	  tipologiaOutro: integer().default(0),
	  contextoIsolado: integer().default(0),
	  contextoBairroSocial: integer().default(0),
	  contextoMeioUrbano: integer().default(0),
	  contextoMeioRural: integer().default(0),
	  segurancaCaes: integer().default(0),
	  segurancaPortaBlindada: integer().default(0),
	  segurancaOutrasMedidas: integer().default(0),
	  avaliador: varchar({ length: 255 }),
	  dataAvaliacao: varchar({ length: 20 }),
	  parecer: text(),
	  observacoes: text(),
	  outrasObservacoes: text(),
	  updatedBy: text(),
	  updatedAt: timestamp({ mode: 'string' }).defaultNow(),
	  pontuacao: integer().default(0).notNull(),
	  neop: varchar({ length: 20 }).notNull(),
	  createdAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
	  cterRequerente: varchar({ length: 50 }),
	  nuipc: varchar({ length: 50 }),
	  entidadeSolicitadora: varchar({ length: 100 }),
	  refFiledoc: varchar({ length: 255 }),
	  email: varchar({ length: 320 }),
	  ordemVerbal: varchar({ length: 255 }),
});

export const notifications = pgTable("notifications", {
	  id: serial().primaryKey().notNull(),
	  operationId: integer().notNull(),
	  userId: integer().notNull(),
	  phoneNumber: varchar({ length: 20 }).notNull(),
	  message: text().notNull(),
	  whatsappLink: text().notNull(),
	  sent: integer().default(0).notNull(),
	  sentAt: timestamp({ mode: 'string' }),
	  createdAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
});

export const operations = pgTable("operations", {
	  id: serial().primaryKey().notNull(),
	  evaluationId: integer().notNull(),
	  userId: integer().notNull(),
	  refFiledoc: varchar({ length: 255 }),
	  operacaoNumero: varchar({ length: 50 }),
	  preenchimentoSecOp: varchar({ length: 50 }),
	  cmdtOp: varchar({ length: 255 }),
	  dataOp: varchar({ length: 20 }),
	  tipoEmpenho: varchar({ length: 50 }),
	  missao: text(),
	  entidadeSolicitadora: varchar({ length: 50 }),
	  local: text(),
	  obsReuniao: text(),
	  gdhSaidaUi: varchar("gdhSaidaUI", { length: 50 }),
	  gdhEntradaUi: varchar("gdhEntradaUI", { length: 50 }),
	  cmdtForcaReuniao: varchar({ length: 255 }),
	  indicativoRadioReuniao: varchar({ length: 50 }),
	  efetivTotalReuniao: varchar({ length: 50 }),
	  viaturasCaracterizadasReuniao: integer().default(0),
	  viaturasDescaracterizadasReuniao: integer().default(0),
	  viaturasEspeciaisReuniao: integer().default(0),
	  kmTotaisReuniao: varchar({ length: 50 }),
	  cterOperacao: varchar({ length: 255 }),
	  dterOperacao: varchar({ length: 255 }),
	  pterZaOperacao: varchar({ length: 255 }),
	  gdhInicioOperacao: varchar({ length: 50 }),
	  gdhChegadaUiOperacao: varchar("gdhChegadaUIOperacao", { length: 50 }),
	  cmdtForcaOperacao: varchar({ length: 255 }),
	  indicativoRadioOperacao: varchar({ length: 50 }),
	  efetivTotalOperacao: varchar({ length: 50 }),
	  viaturasCaracterizadasOperacao: integer().default(0),
	  viaturasDescaracterizadasOperacao: integer().default(0),
	  viaturasEspeciaisOperacao: integer().default(0),
	  kmTotaisOperacao: varchar({ length: 50 }),
	  itpTipo: varchar({ length: 50 }),
	  gdhInicioItp: varchar("gdhInicioITP", { length: 50 }),
	  gdhFimItp: varchar("gdhFimITP", { length: 50 }),
	  forcaTitularInqueritos: integer().default(0),
	  custosPortagens: text(),
	  custosCombustiveis: text(),
	  obsVisados: text(),
	  municoesArmasAuto762: integer().default(0),
	  municoesArmasAuto9Mm: integer("municoesArmasAuto9mm").default(0),
	  municoesArmasAuto762Mm: integer("municoesArmasAuto762mm").default(0),
	  municoesArmasAuto556Mm: integer("municoesArmasAuto556mm").default(0),
	  municoesArmasAuto556: integer().default(0),
	  municoesCacadeiraBarracha: integer().default(0),
	  municoesCacadeiraChumbo: integer().default(0),
	  municoesCacadeiraBeamBag: integer().default(0),
	  municoesCacadeiraZagalote: integer().default(0),
	  municoesCacadeiraZinco: integer().default(0),
	  municoesRevolverAsp: integer("municoesRevolverASP").default(0),
	  taserCargaX26: integer().default(0),
	  taserGranadaFlashBang1Estalo: integer().default(0),
	  taserGranadaFlashBang1Estalo2Bang: integer().default(0),
	  taserGranadaFlashBang2Estalos2Bangs: integer().default(0),
	  taserGranadaFlashBangMultiplos: integer().default(0),
	  taserAlgemas: varchar({ length: 50 }),
	  obsConsumos: text(),
	  obsSecOp: text("obsSECOp"),
	  regSecOp: varchar("regSECOp", { length: 255 }),
	  excelSecOp: integer("excelSECOp").default(0),
	  apontamentosNotas: text(),
	  croquis: text(),
	  createdAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
	  assignedUserId: integer(),
	  scheduledDate: varchar({ length: 20 }),
	  operacaoPreenchida: integer().default(0).notNull(),
	  consumosPreenchidos: integer().default(0).notNull(),
	  observacoesPreenchidas: integer().default(0).notNull(),
	  flaggedForCompletion: integer().default(0).notNull(),
	  flaggedAt: timestamp({ mode: 'string' }),
});

export const suspects = pgTable("suspects", {
	  id: serial().primaryKey().notNull(),
	  evaluationId: integer().notNull(),
	  nome: varchar({ length: 255 }),
	  dataNascimento: varchar({ length: 20 }),
	  nacionalidade: varchar({ length: 100 }),
	  nif: varchar({ length: 20 }),
	  cc: varchar({ length: 20 }),
	  morada: text(),
	  observacoes: text(),
	  createdAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
});

export const users = pgTable("users", {
	  id: serial().primaryKey().notNull(),
	  openId: varchar({ length: 64 }).notNull(),
	  name: text(),
	  email: varchar({ length: 320 }),
	  loginMethod: varchar({ length: 64 }),
	  role: roleEnum().default("user").notNull(),
	  createdAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
	  updatedAt: timestamp({ mode: 'string' }).defaultNow().notNull(),
	  lastSignedIn: timestamp({ mode: 'string' }).defaultNow().notNull(),
	  approved: integer().default(0).notNull(),
	  phoneNumber: varchar({ length: 20 }),
	  mecanographicNumber: varchar({ length: 10 }),
	  rank: varchar({ length: 50 }),
},
							 (table) => [
								   uniqueIndex("users_openId_unique").on(table.openId),
								 ]);

export type Suspect = typeof suspects.$inferSelect;
export type InsertSuspect = typeof suspects.$inferInsert;

export type Operation = typeof operations.$inferSelect;
export type InsertOperation = typeof operations.$inferInsert;

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

export type Evaluation = typeof evaluations.$inferSelect;
export type InsertEvaluation = typeof evaluations.$inferInsert;
