import { mysqlTable, mysqlSchema, AnyMySqlColumn, int, varchar, text, timestamp, tinyint, index, mysqlEnum } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const evaluations = mysqlTable("evaluations", {
	id: int().autoincrement().notNull(),
	userId: int().notNull(),
	pocPosto: varchar({ length: 255 }),
	pocNome: varchar({ length: 255 }),
	pocContacto: varchar({ length: 255 }),
	despacho: text(),
	mandadoDetencao: int().default(0),
	mandadoBusca: int().default(0),
	quantidadeSuspeitos: varchar({ length: 10 }),
	modalidadeIsolado: int().default(0),
	modalidadeAssociacao: int().default(0),
	tipoCriminal: varchar({ length: 255 }),
	antecedentesContraPessoas: int().default(0),
	antecedentesContraPatrimonio: int().default(0),
	antecedentesOutros: int().default(0),
	antecedentesFss: varchar({ length: 10 }),
	posseArma: varchar({ length: 50 }),
	usoArma: varchar({ length: 50 }),
	tipologiaApartamento: int().default(0),
	tipologiaMoradia: int().default(0),
	tipologiaOutro: int().default(0),
	contextoIsolado: int().default(0),
	contextoBairroSocial: int().default(0),
	contextoMeioUrbano: int().default(0),
	contextoMeioRural: int().default(0),
	segurancaCaes: int().default(0),
	segurancaPortaBlindada: int().default(0),
	segurancaOutrasMedidas: int().default(0),
	avaliador: varchar({ length: 255 }),
	dataAvaliacao: varchar({ length: 20 }),
	parecer: text(),
	observacoes: text(),
	outrasObservacoes: text(),
	updatedBy: text(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow(),
	pontuacao: int().default(0).notNull(),
	neop: varchar({ length: 20 }).notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	cterRequerente: varchar({ length: 50 }),
	nuipc: varchar({ length: 50 }),
	entidadeSolicitadora: varchar({ length: 100 }),
	refFiledoc: varchar({ length: 255 }),
	email: varchar({ length: 320 }),
	ordemVerbal: varchar({ length: 255 }),
});

export const notifications = mysqlTable("notifications", {
	id: int().autoincrement().notNull(),
	operationId: int().notNull(),
	userId: int().notNull(),
	phoneNumber: varchar({ length: 20 }).notNull(),
	message: text().notNull(),
	whatsappLink: text().notNull(),
	sent: tinyint().default(0).notNull(),
	sentAt: timestamp({ mode: 'string' }),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export const operations = mysqlTable("operations", {
	id: int().autoincrement().notNull(),
	evaluationId: int().notNull(),
	userId: int().notNull(),
	refFiledoc: varchar({ length: 255 }),
	operacaoNumero: varchar({ length: 50 }),
	preenchimentoSecOp: varchar({ length: 50 }),
	cmdtOp: varchar({ length: 255 }),
	dataOp: varchar({ length: 20 }),
	tipoEmpenho: varchar({ length: 50 }),
	missao: text(),
	entidadeSolicitadora: varchar({ length: 50 }),
	local: text(),
	obsReuniao: text(),
	gdhSaidaUi: varchar({ length: 50 }),
	gdhEntradaUi: varchar({ length: 50 }),
	cmdtForcaReuniao: varchar({ length: 255 }),
	indicativoRadioReuniao: varchar({ length: 50 }),
	efetivTotalReuniao: varchar({ length: 50 }),
	viaturasCaracterizadasReuniao: int().default(0),
	viaturasDescaracterizadasReuniao: int().default(0),
	viaturasEspeciaisReuniao: int().default(0),
	kmTotaisReuniao: varchar({ length: 50 }),
	cterOperacao: varchar({ length: 255 }),
	dterOperacao: varchar({ length: 255 }),
	pterZaOperacao: varchar({ length: 255 }),
	gdhInicioOperacao: varchar({ length: 50 }),
	gdhChegadaUiOperacao: varchar({ length: 50 }),
	cmdtForcaOperacao: varchar({ length: 255 }),
	indicativoRadioOperacao: varchar({ length: 50 }),
	efetivTotalOperacao: varchar({ length: 50 }),
	viaturasCaracterizadasOperacao: int().default(0),
	viaturasDescaracterizadasOperacao: int().default(0),
	viaturasEspeciaisOperacao: int().default(0),
	kmTotaisOperacao: varchar({ length: 50 }),
	itpTipo: varchar({ length: 50 }),
	gdhInicioItp: varchar({ length: 50 }),
	gdhFimItp: varchar({ length: 50 }),
	forcaTitularInqueritos: int().default(0),
	custosPortagens: text(),
	custosCombustiveis: text(),
	obsVisados: text(),
	municoesArmasAuto762: int().default(0),
	municoesArmasAuto9Mm: int().default(0),
	municoesArmasAuto762Mm: int().default(0),
	municoesArmasAuto556Mm: int().default(0),
	municoesArmasAuto556: int().default(0),
	municoesCacadeiraBarracha: int().default(0),
	municoesCacadeiraChumbo: int().default(0),
	municoesCacadeiraBeamBag: int().default(0),
	municoesCacadeiraZagalote: int().default(0),
	municoesCacadeiraZinco: int().default(0),
	municoesRevolverAsp: int().default(0),
	taserCargaX26: int().default(0),
	taserGranadaFlashBang1Estalo: int().default(0),
	taserGranadaFlashBang1Estalo2Bang: int().default(0),
	taserGranadaFlashBang2Estalos2Bangs: int().default(0),
	taserGranadaFlashBangMultiplos: int().default(0),
	taserAlgemas: varchar({ length: 50 }),
	obsConsumos: text(),
	obsSecOp: text(),
	regSecOp: varchar({ length: 255 }),
	excelSecOp: tinyint().default(0),
	apontamentosNotas: text(),
	croquis: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	assignedUserId: int(),
	scheduledDate: varchar({ length: 20 }),
	operacaoPreenchida: tinyint().default(0).notNull(),
	consumosPreenchidos: tinyint().default(0).notNull(),
	observacoesPreenchidas: tinyint().default(0).notNull(),
	flaggedForCompletion: tinyint().default(0).notNull(),
	flaggedAt: timestamp({ mode: 'string' }),
});

export const suspects = mysqlTable("suspects", {
	id: int().autoincrement().notNull().primaryKey(),
	evaluationId: int().notNull(),
	nome: varchar({ length: 255 }),
	dataNascimento: varchar({ length: 20 }),
	nacionalidade: varchar({ length: 100 }),
	nif: varchar({ length: 20 }),
	cc: varchar({ length: 20 }),
	morada: text(),
	observacoes: text(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
});

export type Suspect = typeof suspects.$inferSelect;
export type InsertSuspect = typeof suspects.$inferInsert;

export const users = mysqlTable("users", {
	id: int().autoincrement().notNull(),
	openId: varchar({ length: 64 }).notNull(),
	name: text(),
	email: varchar({ length: 320 }),
	loginMethod: varchar({ length: 64 }),
	role: mysqlEnum(['user','admin']).default('user').notNull(),
	createdAt: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	updatedAt: timestamp({ mode: 'string' }).defaultNow().onUpdateNow().notNull(),
	lastSignedIn: timestamp({ mode: 'string' }).default('CURRENT_TIMESTAMP').notNull(),
	approved: tinyint().default(0).notNull(),
	phoneNumber: varchar({ length: 20 }),
	mecanographicNumber: varchar({ length: 10 }),
	rank: varchar({ length: 50 }),
},
(table) => [
	index("users_openId_unique").on(table.openId),
]);
